repository_type: modules
org_path: self
bump-versions:
  rseqc/junctionannotation: False
  rseqc/bamstat: False
  rseqc/readduplication: False
  rseqc/readdistribution: False
  rseqc/junctionsaturation: False
  rseqc/inferexperiment: False
  rseqc/innerdistance: False
  sortmerna: False
